### ISSUE TITLE
Not able to get it to connect to wifi

### ISSUE THREAD

**Issue by nikki-reprap** [NorthernMan54/nodemcu-dht-yl69-json-mdns#3]
I upload all the files and upload test.lua last it boots up but i get the following error 

NodeMCU custom build by frightanic.com
	branch: master
	commit: 2e67ff5a639a13260fd4fb3c3b627ccdc2845616
	SSL: false
	modules: adc,bit,bme280,dht,file,gpio,i2c,mdns,net,node,tmr,uart,wifi
 build 	built on: 2017-09-09 09:38
 powered by Lua 5.1.4 on SDK 2.1.0(116b762)
Booting...
Setting Init Timer
Configuring Wifi ...
> PANIC: unprotected error in call to Lua API (setup.lua:37: bad argument #1 to 'config' (config table not found!))

**Comment by NorthernMan54** [comment]
Looks like the config is missing your SSID and Password

Line 37 in setup.lua is this

wifi.sta.config(key,config.SSID[key])

Have you updated config.lua with your SSID and Password i.e.

module.SSID["network name"] = "password"

**Comment by nikki-reprap** [comment]
Yes I have put my ssid and password in configure.lua is there a particular order I need to upload the files ?

**Comment by NorthernMan54** [comment]
No, there is no particular order for uploading files.  I'm thinking a typo in that portion of your config.lua.  Does your SSID have funny characters maybe

**Comment by NorthernMan54** [comment]
PS The config.lua in the repository has both my hotspots listed....  I need to clean that up

**Comment by NorthernMan54** [comment]
Can you share your config.lua ?

**Comment by nikki-reprap** [comment]
local module = {}

module.SSID = {}
module.SSID["belkin.c1c"] = "armory1981"
module.SSID["The_Beach"] = "brownieg"

-- Options are DHT or DHT-YL, used by homebridge to determine if moisture data is valid.
module.Model = "BME-GD"
module.Version = "1.3"

module.ID = wifi.sta.gethostname()

module.ledRed = 0 -- gpio16
module.ledBlue = 4 -- gpio2
module.sensor = 7 -- gpio14

module.bme280scl = 5  -- D5
module.bme280sda = 6  -- D6

module.DHT22 = 2
module.YL69 = 0 -- adc pin 0

return module

**Comment by NorthernMan54** [comment]
Looks like the nodemcu command format changed since I built this.   Change your SSID entry in config.lua to

module.SSID["belkin.c1c"] = { ssid="belkin.c1c", pwd = "armory1981" }

And change line 37 in setup.lua to

wifi.sta.config(passwords.SSID[key])

That should work

**Comment by nikki-reprap** [comment]
Thank you it works perfectly now

**Comment by nikki-reprap** [comment]
there is now one more problem it never updates from this
{ "Hostname": "NODE-248E40", "Model": "BME", "Version": "1.3", "Firmware": "2.1.0", "Data": {"Temperature": -999, "Humidity": -999, "Moisture": 5, "Status": 1, "Barometer": -999, "Dew": -999 }}

Is there a way to set the i2c address ?

**Comment by NorthernMan54** [comment]
Yes, the i2c address for the bme280 is set in config.lua. 

module.bme280scl = 5 -- D5
module.bme280sda = 6 -- D6

**Comment by nikki-reprap** [comment]
Thanks
